EXAMPLE_SENTENCES = ["Mr. Johnson bought a new car.",
                     "Sarah visited her grandmother.",
                     "The dog chased its tail.",
                     "Dr. Parker examined the patient.",
                     "We went swimming in the lake.",
                     "Lisa baked a delicious cake.",
                     "The train arrived on time.",
                     "Mr. Davis walked his dog.",
                     "Emily played the piano beautifully.",
                     "The sun set behind the mountains.",
                     "Dr. Reynolds gave a fascinating lecture.",
                     "Sam rode his bike to school.",
                     "The cat purred contentedly.",
                     "Jessica finished her homework early.",
                     "The flowers bloomed in the garden.",
                     "Mr. Anderson mowed his lawn.",
                     "David fixed the broken window.",
                     "Dr. Martinez conducted a research study.",
                     "The children laughed and played.",
                     "Emma read a captivating novel.",
                     "The rain stopped suddenly.",
                     "Mr. Thompson cooked dinner for his family.",
                     "Rachel painted a stunning portrait.",
                     "The birds chirped in the trees.",
                     "Dr. Adams wrote a scholarly article.",
                     "Mark ran a marathon.",
                     "The fire crackled in the fireplace.",
                     "Olivia studied for her exams.",
                     "The butterfly landed on a flower.",
                     "Mr. Rodriguez coached the soccer team.",
                     "Lily danced gracefully on stage.",
                     "The wind rustled through the leaves.",
                     "Dr. Collins examined the x-ray.",
                     "Jason built a sandcastle at the beach.",
                     "The baby smiled for the first time.",
                     "Mr. Carter fixed the leaky faucet.",
                     "Megan hiked up the mountain trail.",
                     "The clock ticked slowly.",
                     "Dr. Walker administered a flu shot.",
                     "Andrew played guitar in a band.",
                     "The waves crashed against the shore.",
                     "Mrs. Turner baked fresh bread.",
                     "Eric repaired the broken bicycle.",
                     "Dr. Hughes diagnosed the patient's illness.",
                     "Sarah knitted a cozy sweater.",
                     "The thunder rumbled in the distance.",
                     "Mr. Mitchell taught a history class.",
                     "Rebecca wrote a heartfelt letter.",
                     "The leaves changed color in the fall.",
                     "Dr. Foster performed surgery.",
                     "Alex caught a fish in the river.",
                     "The crowd cheered at the concert.",
                     "Mrs. Evans watered her plants.",
                     "Michael cooked a delicious meal.",
                     "The owl hooted in the night.",
                     "Dr. Thompson conducted a psychology experiment.",
                     "Emily studied for her math test.",
                     "The snowflakes fell gently from the sky.",
                     "Mr. Roberts fixed the car engine.",
                     "Samantha painted a beautiful landscape.",
                     "The bees buzzed around the flowers.",
                     "Dr. Baker delivered a baby.",
                     "Daniel played soccer with his friends.",
                     "The fireflies blinked in the darkness.",
                     "Mrs. Phillips taught an art class.",
                     "James wrote a poem for his girlfriend.",
                     "The waterfall cascaded down the rocks.",
                     "Dr. Nguyen performed a dental procedure.",
                     "Jennifer baked cookies for her neighbors.",
                     "The crickets chirped in the evening.",
                     "Mr. Thompson repaired the roof.",
                     "Stephanie danced ballet on stage.",
                     "The fog rolled in from the sea.",
                     "Dr. Patel prescribed medication for the patient.",
                     "Kevin built a sandcastle at the beach.",
                     "The birds sang their melodious songs.",
                     "Mrs. Lewis sewed a quilt.",
                     "Jason grilled burgers for the barbecue.",
                     "The wind howled through the trees.",
                     "Dr. Wright conducted a scientific experiment.",
                     "Amanda studied for her history exam.",
                     "The snow covered the landscape in white.",
                     "Mr. Foster fixed the broken computer.",
                     "Nicole painted a vibrant mural.",
                     "The crickets chirped in the meadow.",
                     "Dr. Thompson performed a heart surgery.",
                     "Matthew played basketball with his friends.",
                     "The stars twinkled in the night sky.",
                     "Mrs. Turner taught a cooking class.",
                     "Brian cooked a delicious dinner.",
                     "The waves gently lapped against the shore.",
                     "Dr. Miller diagnosed the patient's condition.",
                     "Samantha knitted a cozy scarf.",
                     "The thunder boomed loudly.",
                     "Mr. Johnson coached the basketball team.",
                     "Rebecca wrote a captivating story.",
                     "The leaves rustled in the wind.",
                     "Dr. Foster treated a patient's broken bone.",
                     "Adam caught a ball during the game.",
                     "The crowd erupted with applause.",
                     "Mrs. Anderson painted a beautiful mural.", "The dog barked loudly at the mailman.",
                     "Dr. Thompson analyzed the research data.", "John and Emily went on a hiking trip.",
                     "The sunflower blossomed in the garden.", "Mr. Martinez taught a chemistry class.",
                     "Emma and Ethan danced at the party.", "The wind whispered through the trees.",
                     "Dr. Collins performed a surgery successfully.", "Sophia and Daniel enjoyed a picnic in the park.",
                     "The fireflies illuminated the night sky.", "Mrs. Johnson planted vegetables in her backyard.",
                     "Robert fixed the flat tire on his bicycle.", "Dr. Davis gave a motivational speech.",
                     "Oliver and Mia built a sandcastle on the beach.", "The rainbows appeared after the rain.",
                     "Mr. Turner brewed a fresh cup of coffee.", "Grace played the violin with great passion.",
                     "The dolphins swam gracefully in the ocean.",
                     "Dr. Walker treated patients with care and compassion.",
                     "Liam and Olivia explored the ancient ruins.", "The candle flickered in the dark room.",
                     "Mrs. Parker organized a charity event.", "Jackson and Lily had a fun day at the amusement park.",
                     "The autumn leaves danced in the breeze.", "Dr. Adams conducted an experiment in the laboratory.",
                     "Sophie and William baked cookies for their friends.", "The moonlight illuminated the night sky.",
                     "Mr. Evans fixed the broken gate in the backyard.",
                     "Isabella and Jacob sang a duet at the concert.", "The snowflakes glistened in the sunlight.",
                     "Dr. Phillips examined the patient's condition carefully.",
                     "Ella and Benjamin went on a road trip.", "The peacock displayed its vibrant feathers.",
                     "Mrs. Foster crafted a beautiful sculpture.", "Henry and Mia played a game of chess.",
                     "The campfire crackled and warmed the campers.",
                     "Dr. Turner conducted a groundbreaking research study.",
                     "Lucas and Emily enjoyed a boat ride on the lake.", "The shooting stars dazzled in the night sky.",
                     "Mr. Baker taught a cooking class for beginners.", "Aiden and Sophia prepared a delicious meal.",
                     "The gentle breeze swayed the tall grass.",
                     "Dr. Lewis delivered a heartfelt speech at the conference.",
                     "Daniel and Ava went on a wildlife safari.", "The full moon illuminated the dark night.",
                     "Mrs. Mitchell sculpted a beautiful statue.", "James and Olivia solved a challenging puzzle.",
                     "The bonfire warmed everyone on a cold evening.",
                     "Dr. Wright published a groundbreaking scientific paper.",
                     "Noah and Lily went on an adventurous hike.", "The rainbow painted a colorful arc across the sky.",
                     "Mr. Harris painted a serene landscape.", "Emily and Ethan danced the tango at the ballroom.",
                     "The gentle waves kissed the sandy shore.", "Dr. Carter administered a life-saving treatment.",
                     "Sophia and Oliver enjoyed a scenic bike ride.", "The stars sparkled in the clear night sky.",
                     "Mrs. Miller baked a batch of delicious cupcakes.", "Alexander and Mia explored the deep sea.",
                     "The candle flame danced gracefully.", "Dr. Patel offered medical advice to the patients.",
                     "Emma and Benjamin created a beautiful artwork.",
                     "The river flowed peacefully through the valley.",
                     "Mr. Thompson organized a successful charity fundraiser.",
                     "Charlotte and Lucas enjoyed a day at the zoo.", "The cherry blossoms bloomed in the spring.",
                     "Dr. Foster conducted an in-depth research analysis.",
                     "Grace and Ethan danced under the starry sky.", "The waterfall cascaded down the rocky cliffs.",
                     "Mrs. Wright painted a realistic portrait.", "Henry and Olivia solved a complex math problem.",
                     "The bonfire crackled and emitted a warm glow.",
                     "Dr. Turner presented the findings at a scientific conference.",
                     "Emily and William embarked on a thrilling adventure.",
                     "The fireworks illuminated the night sky with bursts of color.",
                     "Mr. Baker taught an advanced cooking technique.",
                     "Sophia and Daniel crafted intricate origami creations.",
                     "The gentle breeze rustled the leaves on the trees.",
                     "Dr. Lewis delivered a powerful keynote speech.",
                     "Emma and Benjamin discovered rare species in the rainforest.",
                     "The full moon cast a mesmerizing glow.", "Mrs. Mitchell sketched a detailed portrait.",
                     "James and Olivia composed a beautiful melody.",
                     "The campfire crackled and provided warmth on a chilly night.",
                     "Dr. Wright conducted an extensive research experiment.",
                     "Noah and Lily spotted exotic birds during their nature walk.",
                     "The rainbow arched across the sky in vibrant colors.", "Mr. Harris painted a serene seascape.",
                     "Emily and Ethan waltzed gracefully on the dance floor.",
                     "The gentle waves lapped against the sandy beach.", "Dr. Carter performed a life-saving surgery.",
                     "Sophia and Oliver admired breathtaking views during their hike.",
                     "The stars shimmered brightly in the night sky.", "Mrs. Miller baked a scrumptious apple pie.",
                     "Alexander and Mia explored the wonders of the coral reef.", "The candle flame flickered softly.",
                     "Dr. Patel provided compassionate care to her patients.",
                     "Emma and Benjamin collaborated on an impressive art project.",
                     "The river meandered through the picturesque landscape.",
                     "Mr. Thompson organized a successful community event.",
                     "Charlotte and Lucas marveled at the exotic animals in the safari.",
                     "The cherry blossoms painted a beautiful scene in the garden.",
                     "Dr. Foster analyzed complex data for her research.",
                     "Grace and Ethan twirled under the moonlit sky.",
                     "The waterfall roared as it plunged into the pool below.",
                     "Mrs. Wright sculpted a lifelike clay figure.",
                     "Mr. Thompson greeted his students with a smile.",
                     "Sophia and Benjamin explored the hidden cave.",
                     "The waves crashed against the rocky shoreline.",
                     "Dr. Evans conducted groundbreaking research in astrophysics.",
                     "Olivia played the violin at the prestigious concert hall.",
                     "The scent of freshly baked cookies filled the kitchen.",
                     "Mrs. Parker taught a captivating history lesson.",
                     "Jackson and Emily built a towering sandcastle on the beach.",
                     "The autumn leaves swirled in the crisp breeze.",
                     "Dr. Mitchell discovered a new species of marine life.",
                     "Nathan and Mia embarked on a thrilling roller coaster ride.",
                     "The raindrops pitter-pattered on the windowpane.",
                     "Mr. Turner brewed a steaming cup of aromatic coffee.",
                     "Isabella performed a breathtaking ballet routine.",
                     "The wind whispered secrets among the tall trees.",
                     "Dr. Davis examined the patient's condition with precision.",
                     "Matthew and Lily enjoyed a scenic hike in the mountains.",
                     "The bonfire crackled and illuminated the night sky.",
                     "Mrs. Baker organized a successful charity fundraiser.",
                     "Lucas and Olivia solved a complex puzzle together.",
                     "The snowflakes danced in the air, creating a winter wonderland.",
                     "Dr. Phillips delivered an inspiring motivational speech.",
                     "Ethan and Sophia shared a romantic candlelit dinner.",
                     "The river flowed peacefully through the lush green valley.",
                     "Mr. Foster painted a breathtaking landscape on his canvas.",
                     "Grace and Benjamin danced under the starry night sky.",
                     "The fireflies created a magical glow in the moonlit garden.",
                     "Mrs. Turner prepared a delectable feast for her guests.",
                     "Henry and Emily explored the ancient ruins of a forgotten civilization.",
                     "The gentle breeze rustled the colorful autumn leaves.",
                     "Dr. Harris conducted a groundbreaking experiment in neuroscience.",
                     "Sophie and Noah enjoyed a scenic boat ride on the serene lake.",
                     "The shooting stars streaked across the midnight sky in a celestial spectacle.",
                     "Mr. Roberts crafted a beautiful wooden sculpture.",
                     "Ava and Daniel sang a heartfelt duet at the grand concert.",
                     "The sunflower fields stretched as far as the eye could see.",
                     "Dr. Nguyen provided compassionate care to her patients.",
                     "Emma and Lucas created intricate paper origami art.",
                     "The thunder echoed through the valleys, signaling an approaching storm.",
                     "Mrs. Miller captured a stunning photograph of a cascading waterfall.",
                     "James and Mia solved a challenging math problem together.",
                     "The bonfire crackled and warmed the gathering of friends.",
                     "Dr. Thompson presented his groundbreaking research findings at a prestigious conference.",
                     "Sophia and Ethan embarked on an unforgettable cross-country road trip.",
                     "The fireworks exploded in a burst of vibrant colors and patterns.",
                     "Mr. Davis taught a masterclass in culinary arts.",
                     "Olivia and Benjamin crafted beautiful pottery on the pottery wheel.",
                     "The gentle waves washed ashore, leaving behind seashells and memories.",
                     "Dr. Collins performed a life-saving surgery with utmost precision.",
                     "Emily and Matthew explored a hidden gem in the heart of the city.",
                     "The rainbow stretched across the sky, painting a vivid arch of colors.",
                     "Mrs. Lewis painted a stunning portrait capturing the essence of her subject.",
                     "Henry and Ava composed a heartfelt song together.",
                     "The crackling campfire provided warmth and comfort on a chilly night.",
                     "Dr. Wright conducted groundbreaking research in quantum physics.",
                     "Noah and Lily embarked on a thrilling zip-lining adventure.",
                     "The moon cast a soft glow, illuminating the night landscape.",
                     "Mr. Baker prepared a mouthwatering gourmet meal for his guests.",
                     "Sophia and Daniel hiked to the summit of a breathtaking mountain.",
                     "The stars twinkled like diamonds in the clear night sky.",
                     "Mrs. Phillips crafted a beautiful stained glass artwork.",
                     "James and Olivia solved a challenging crossword puzzle.",
                     "The bonfire crackled, casting a warm glow on the faces of friends.",
                     "Dr. Foster made significant breakthroughs in cancer research.",
                     "Emma and William set sail on a thrilling sailing expedition.",
                     "The rainbow painted a vibrant arc across the sky, mesmerizing all who beheld it.",
                     "Mr. Harris created a stunning masterpiece on his canvas.",
                     "Emily and Ethan danced under the moonlight, their steps filled with grace.",
                     "The gentle waves kissed the sandy shoreline, creating a soothing melody.",
                     "Dr. Carter performed a complex surgical procedure with utmost expertise.",
                     "Sophia and Oliver embarked on a thrilling skydiving adventure.",
                     "The stars shimmered brightly, lighting up the night with their cosmic glow.",
                     "Mrs. Miller baked a mouthwatering chocolate cake from scratch.",
                     "Alexander and Mia explored the vibrant coral reefs teeming with marine life.",
                     "The candle flame flickered gently, casting a warm ambiance in the room.",
                     "Dr. Patel provided compassionate care to her patients, offering comfort and reassurance.",
                     "Emma and Benjamin collaborated on a stunning art installation that captivated viewers.",
                     "The river meandered through the picturesque landscape, carrying secrets of the land.",
                     "Mr. Thompson organized a community volunteer event, bringing people together for a good cause.",
                     "Charlotte and Lucas marveled at the majestic elephants during their safari adventure.",
                     "Mr. Anderson planted a beautiful rose garden in his backyard.",
                     "Sophia and Benjamin embarked on an exciting treasure hunt.",
                     "The waves crashed against the rugged cliffs, sending sprays of mist into the air.",
                     "Dr. Evans delivered an inspiring lecture on quantum mechanics.",
                     "Olivia showcased her impressive painting at the art exhibition.",
                     "The aroma of freshly baked bread wafted through the bakery.",
                     "Mrs. Parker organized a captivating science fair for the students.",
                     "Jackson and Emily constructed an elaborate treehouse in their backyard.",
                     "The autumn leaves swirled in a whirlwind of colors.",
                     "Dr. Mitchell discovered a new galaxy through his telescope.",
                     "Nathan and Mia enjoyed a thrilling bungee jumping experience.",
                     "The raindrops created a rhythmic melody on the rooftop.",
                     "Mr. Turner cultivated a vibrant garden filled with blooming flowers.",
                     "Isabella wowed the audience with her stunning ballet performance.",
                     "The wind whispered ancient tales to the swaying trees.",
                     "Dr. Davis meticulously analyzed the patient's medical records.",
                     "Matthew and Lily relished the panoramic views from the mountaintop.",
                     "The bonfire crackled, casting dancing shadows on the faces around it.",
                     "Mrs. Baker organized a successful charity gala to support a worthy cause.",
                     "Lucas and Olivia deciphered the secrets of an ancient treasure map.",
                     "The snowflakes fell gently, blanketing the landscape in a pristine white.",
                     "Dr. Phillips delivered a captivating keynote speech at the conference.",
                     "Ethan and Sophia stargazed under the clear night sky, identifying constellations.",
                     "The river meandered lazily, reflecting the beauty of the surrounding nature.",
                     "Mr. Foster captured the essence of a majestic mountain range in his painting.",
                     "Grace and Benjamin waltzed gracefully across the dance floor.",
                     "The fireflies illuminated the darkness, creating a magical ambiance.",
                     "Mrs. Turner meticulously prepared a mouthwatering feast for her guests.",
                     "Henry and Emily explored an enchanting fairy-tale forest on their adventure.",
                     "The gentle breeze rustled the golden leaves, painting a scenic autumn landscape.",
                     "Dr. Harris conducted groundbreaking experiments in genetic engineering.",
                     "Sophie and Noah sailed across the pristine waters, discovering hidden islands.",
                     "The shooting stars streaked across the night sky, granting wishes to all who witnessed them.",
                     "Mr. Roberts sculpted an intricate masterpiece from a solid block of marble.",
                     "Ava and Daniel harmonized their voices, creating a beautiful melody.",
                     "The sunflower fields stretched as far as the eye could see, bathing the landscape in vibrant yellow.",
                     "Dr. Nguyen provided exceptional care to her patients, ensuring their well-being.",
                     "Emma and Lucas folded delicate origami cranes, symbolizing peace and good luck.",
                     "The thunder reverberated through the valleys, announcing the arrival of a mighty storm.",
                     "Mrs. Miller captured the magnificence of a cascading waterfall through her lens.",
                     "James and Mia collaborated on an imaginative storytelling project, captivating their audience.",
                     "The bonfire crackled, its warm glow bringing comfort and joy to all gathered around it.",
                     "Dr. Thompson presented groundbreaking findings at a prestigious scientific symposium.",
                     "Sophia and Ethan embarked on a thrilling ziplining adventure, soaring through the treetops.",
                     "The fireworks burst into a spectacular display of colors, painting the night sky with brilliance.",
                     "Mr. Davis shared his culinary expertise, teaching a masterclass in the art of gourmet cooking.",
                     "Olivia and Benjamin intricately weaved a stunning tapestry, reflecting their shared creativity.",
                     "The gentle waves lapped against the sandy shore, creating a soothing symphony of nature.",
                     "Dr. Collins performed a complex surgical procedure with unparalleled skill and precision.",
                     "Emily and Matthew embarked on a captivating journey, exploring the wonders of a hidden gem.",
                     "The rainbow arched across the sky, its vibrant hues igniting a sense of wonder in all who saw it.",
                     "Mrs. Lewis unveiled a captivating sculpture, its form capturing the essence of human emotion.",
                     "Henry and Ava composed a heartfelt song, its melodies resonating with deep emotions.",
                     "The crackling campfire provided warmth and companionship on a chilly night under the starry sky.",
                     "Dr. Wright revolutionized the field of renewable energy through groundbreaking research.",
                     "Noah and Lily embarked on an adrenaline-fueled adventure, bungee jumping from a towering bridge.",

                     "I didn't know what to do, so I called Mr. Johnson.",
                     "She was lost in the city and sought help from Officer Smith.",
                     "The patient needed immediate attention, so we called Dr. Parker.",
                     "We were running late, but luckily Mr. Davis gave us a ride.",
                     "The performance was breathtaking, thanks to Lily's graceful dance.",
                     "The research paper was insightful, written by Dr. Reynolds.",
                     "They were lost in the forest, but fortunately, Emma met a helpful guide.",
                     "The delicious cake was baked by Lisa, the master pastry chef.",
                     "The kids were excited for the trip, especially with Mr. Anderson as their chaperone.",
                     "She played the piano beautifully, mesmerizing the audience, Emily.",
                     "The breathtaking sunset painted the sky, witnessed by all, thanks to the sun behind the mountains.",
                     "The lecture was fascinating, leaving the students inspired, Dr. Foster.",
                     "Sam had a flat tire on his way to school but was helped by a kind passerby, Mr. Mitchell.",
                     "The cat purred contentedly, finding comfort in Jessica's gentle touch.",
                     "The flowers bloomed vibrantly, showcasing nature's beauty in the garden, with Mr. Thompson's diligent care.",
                     "The broken window was fixed promptly by David, the skilled handyman.",
                     "The research study yielded groundbreaking results, led by the renowned scientist, Dr. Martinez.",
                     "The children laughed and played joyfully, under the watchful eye of Mrs. Evans.",
                     "She was captivated by the captivating novel, engrossed in its pages, thanks to Emma's recommendation.",
                     "The sudden rain stopped as abruptly as it started, leaving the streets glistening, much to the relief of Mr. Anderson.",
                     "The delicious aroma filled the kitchen, as Mr. Thompson cooked dinner for his family.",
                     "Rachel's stunning portrait captured the essence of the subject's soul.",
                     "The birds chirped melodiously, serenading the trees with their songs, heard by Dr. Adams during his morning walk.",
                     "Mark's determination and training paid off as he successfully completed the marathon.",
                     "The crackling fire in the fireplace provided warmth and coziness on a cold winter night.",
                     "Olivia's dedication and hours of studying paid off as she aced her exams.",
                     "The delicate butterfly gracefully landed on a flower, catching the attention of all passersby.",
                     "Lily's graceful movements on stage enchanted the audience, leaving them in awe.",
                     "The wind's gentle touch rustled through the leaves, creating a serene ambiance in the park.",
                     "The x-ray showed no signs of fracture, as confirmed by Dr. Collins.",
                     "Jason built a majestic sandcastle at the beach, admired by all who passed by.",
                     "The baby's first smile melted everyone's hearts, especially Mr. Carter's.",
                     "The leaky faucet was fixed promptly by Mr. Carter, the skilled plumber.",
                     "Megan's determination drove her to conquer the challenging mountain trail.",
                     "Alex's patience paid off as he caught a magnificent fish in the river.",
                     "The crowd's cheers reverberated through the concert hall, acknowledging the artists' exceptional performance.",

                     "The dog bounded after the frisbee, cheered on by his owner, Mr. Peterson.",
                     "The city buzzed with life and energy, something that always inspired Dr. Emily during her evening walks.",
                     "The room filled with applause as the team celebrated their win, led by their dedicated coach, Mr. Jackson.",
                     "The science project was a great success, thanks to the invaluable input from Dr. Kim.",
                     "The machine hummed along smoothly, a testament to the skill of its designer, Mr. Adams.",
                     "The music swept through the ballroom, bringing a smile to the face of Mrs. Parker as she watched her students dance.",
                     "The experiment proceeded successfully, under the meticulous guidance of Dr. Emily.",
                     "The children's faces lit up with understanding, thanks to the patience and efforts of Mr. White, their math teacher.",
                     "The performance was breathtaking, thanks to the dedication and talent of the lead actor, Mr. Adams.",
                     "The stars shone brightly in the clear night sky, providing the perfect conditions for Dr. Chen's astronomical observations.",
                     "The event was a resounding success, all due to the tireless efforts of the organizer, Mr. Johnson.",
                     "The garden bloomed with color, thanks to the careful nurturing of Mrs. Patel.",
                     "The film ended to thunderous applause, proving yet again the directing prowess of Mr. Roberts.",
                     "The healing process was smooth and quick, owing to the expertise of Dr. Emily.",
                     "The team achieved their sales target for the third consecutive month, a testament to the leadership of Mr. Adams.",
                     "The space mission was a great success, thanks to the tireless efforts of the mission director, Dr. Cooper.",
                     "The painting was a vivid depiction of a mountain landscape, admired by the museum curator, Mr. Sanchez.",
                     "The dinner was a culinary delight, masterfully prepared by the celebrated chef, Mr. Ramsey.",
                     "The seminar was an enlightening experience, thanks to the eloquent speaker, Dr. Emily.",
                     "The charity event managed to raise a significant amount, all credit goes to the event planner, Mrs. Adams.",
                     "The dog bounded after the frisbee, cheered on by his owner, Mr. Peterson.",
                     "The city buzzed with life and energy, something that always inspired Dr. Emily during her evening walks.",
                     "The room filled with applause as the team celebrated their win, led by their dedicated coach, Mr. Jackson.",
                     "The science project was a great success, thanks to the invaluable input from Dr. Kim.",
                     "The machine hummed along smoothly, a testament to the skill of its designer, Mr. Adams.",
                     "The music swept through the ballroom, bringing a smile to the face of Mrs. Parker as she watched her students dance.",
                     "The experiment proceeded successfully, under the meticulous guidance of Dr. Emily.",
                     "The children's faces lit up with understanding, thanks to the patience and efforts of Mr. White, their math teacher.",
                     "The performance was breathtaking, thanks to the dedication and talent of the lead actor, Mr. Adams.",
                     "The stars shone brightly in the clear night sky, providing the perfect conditions for Dr. Chen's astronomical observations.",
                     "The event was a resounding success, all due to the tireless efforts of the organizer, Mr. Johnson.",
                     "The garden bloomed with color, thanks to the careful nurturing of Mrs. Patel.",
                     "The film ended to thunderous applause, proving yet again the directing prowess of Mr. Roberts.",
                     "The healing process was smooth and quick, owing to the expertise of Dr. Emily.",
                     "The team achieved their sales target for the third consecutive month, a testament to the leadership of Mr. Adams.",
                     "The space mission was a great success, thanks to the tireless efforts of the mission director, Dr. Cooper.",
                     "The painting was a vivid depiction of a mountain landscape, admired by the museum curator, Mr. Sanchez.",
                     "The dinner was a culinary delight, masterfully prepared by the celebrated chef, Mr. Ramsey.",
                     "The seminar was an enlightening experience, thanks to the eloquent speaker, Dr. Emily.",
                     "The charity event managed to raise a significant amount, all credit goes to the event planner, Mrs. Adams.",
                     "The shopping mall was teeming with people, closely observed by the diligent security officer, Mr. Brown.",
                     "The project was completed ahead of schedule, thanks to the efficient management of Dr. Turner.",
                     "The classroom was abuzz with energy, thanks to the engaging teaching style of Mr. Adams.",
                     "The family relished the home-cooked meal, lovingly prepared by Mrs. Thompson.",
                     "The architecture of the building was simply stunning, earning praise from the noted architect, Dr. Emily.",
                     "The art exhibition attracted a large crowd, thanks to the publicity efforts of Mr. Patel.",
                     "The choir sang beautifully, guided by the skilled conductor, Mrs. Adams.",
                     "The play was a huge hit, a result of the creative genius of the director, Mr. Anderson.",
                     "The meeting was well-coordinated and effective, thanks to the organization skills of Dr. Emily.",
                     "The city park was clean and well-maintained, all due to the hard work of Mr. Rodriguez.",
                     "The house was beautifully decorated for the holiday season, thanks to the efforts of Mrs. Baker.",
                     "The charity drive was successful, collecting a substantial amount, coordinated by Mr. Adams.",
                     "The book club discussion was insightful, moderated by the knowledgeable Dr. Emily.",
                     "The cake was moist and delicious, baked to perfection by Mrs. Martin.",
                     "The fundraising event exceeded all expectations, due to the excellent planning of Mr. Anderson.",
                     "The presentation was crisp and clear, reflecting the hard work of Dr. Emily.",
                     "The concert was unforgettable, thanks to the phenomenal performance of the band, managed by Mr. Adams.",
                     "The party was a hit, filled with fun and laughter, thanks to the entertaining games planned by Mrs. Thompson.",
                     "The historic site was well-preserved, thanks to the diligent efforts of Dr. Emily.",
                     "The debate was heated yet respectful, moderated effectively by Mr. Adams.",
                     "The cycling event went smoothly, thanks to the excellent route planning of Mr. Baker.",
                     "The vintage car was well-maintained, a result of Mr. Adams's love for classic vehicles.",
                     "The long-distance run was tough but fulfilling, organized flawlessly by Mrs. Johnson.",
                     "The building was renovated to its former glory, overseen by the experienced architect, Dr. Emily.",
                     "The research paper was highly acclaimed, reflecting the dedication and intellect of Mr. Adams.",
                     "The student exchange program was a success, thanks to the meticulous planning of Mrs. Martin.",
                     "The ice sculpture was a work of art, admired by the event attendees, crafted by Mr. Adams.",
                     "The floral arrangement was gorgeous, thanks to the creative vision of Mrs. Parker.",
                     "The poetry recital was a wonderful event, organized by the literature enthusiast, Dr. Emily.",
                     "The crime scene was thoroughly investigated by the experienced detective, Mr. Adams.",
                     "The radio show was popular among listeners, thanks to the charismatic host, Mrs. Thompson.",
                     "The coding workshop was informative and engaging, conducted by the talented programmer, Dr. Emily.",
                     "The movie premiere was a grand event, organized to perfection by Mr. Adams.",
                     "The school play was a resounding success, thanks to the hard work of Mrs. Wilson.",
                     "The zoo was well-managed and cared for, due to the tireless efforts of Mr. Adams.",
                     "The college fair was well-attended, thanks to the efficient organizing of Dr. Emily.",
                     "The birthday party was filled with joy and laughter, made special by Mrs. Thompson's efforts.",
                     "The photo exhibit showcased breathtaking images, curated by the talented photographer, Mr. Adams.",
                     "The wine tasting event was classy and enjoyable, hosted by the connoisseur, Mrs. Wilson.",
                     "The city tour was informative and fun, led by the knowledgeable guide, Mr. Adams.",
                     "The community outreach program was impactful, thanks to the effective planning of Dr. Emily.",
                     "The training session was productive and insightful, conducted by the seasoned coach, Mr. Adams.",
                     "The road was kept clean and litter-free, thanks to the diligent work of Mr. Thompson.",
                     "The fishing trip was fun and relaxing, planned by the outdoor enthusiast, Mrs. Parker.",
                     "The art workshop was educational and inspiring, taught by the experienced artist, Dr. Emily.",
                     "The hiking trip was adventurous and safe, guided by the experienced trekker, Mr. Adams.",
                     "The music festival was a hit, organized flawlessly by the event management company led by Mrs. Thompson.",
                     "The annual fair was fun and festive, thanks to the effective coordination of Mr. Adams.",
                     "The seminar was informative and engaging, thanks to the knowledgeable speaker, Dr. Emily.",
                     "The carnival was colorful and vibrant, managed by the enthusiastic event planner, Mrs. Adams.",
                     "The greenhouse was lush and healthy, maintained by the passionate gardener, Mr. Thompson.",
                     "The town hall meeting was orderly and productive, overseen by the mayor, Mr. Adams.",]



EXAMPLE_QUESTIONS = [
"Did you enjoy the music at the party, Mr. Adams?",
"Can you explain this concept further, Dr. Emily?",
"When will the next match take place, Coach Johnson?",
"Where did you learn these skills, Mr. Thompson?",
"How did you manage to complete this project on time, Dr. Martinez?",
"What was the inspiration behind your latest book, Mrs. Parker?",
"Could you tell us more about your research, Dr. Emily?",
"What's the secret of your famous pasta recipe, Chef Adams?",
"What were your initial challenges in this profession, Mr. Thompson?",
"Can you explain the significance of this painting, Dr. Emily?",
"What was your strategy behind the successful marketing campaign, Mr. Adams?",
"How can we implement sustainable practices in our daily lives, Dr. Green?",
"What were your observations during the space mission, Astronaut Thompson?",
"How did you come up with this innovative business idea, Mr. Adams?",
"Can you explain the process behind this scientific breakthrough, Dr. Emily?",
"What's your favorite part about teaching, Professor Thompson?",
"Could you tell us about your journey in the music industry, Mr. Adams?",
    "Who painted a beautiful mural?",
    "What made the dog bark loudly?",
    "Whose research data did Dr. Thompson analyze?",
    "Who went on a hiking trip together?",
    "Where did the sunflower blossom?",
    "Who taught a chemistry class?",
    "Who danced at the party?",
    "What whispered through the trees?",
    "What did Dr. Collins perform successfully?",
    "Who enjoyed a picnic in the park?",
    "What illuminated the night sky?",
    "Who planted vegetables in her backyard?",
    "Who fixed the flat tire on his bicycle?",
    "Who gave a motivational speech?",
    "Who built a sandcastle on the beach?",
    "What appeared after the rain?",
    "Who brewed a fresh cup of coffee?",
    "Who played the violin with great passion?",
    "What swam gracefully in the ocean?",
    "Who treated patients with care and compassion?",
    "Who explored the ancient ruins?",
    "What flickered in the dark room?",
    "What event did Mrs. Parker organize?",
    "Who had a fun day at the amusement park?",
    "What danced in the breeze?",
    "Whose experiment did Dr. Adams conduct in the laboratory?",
    "Who baked cookies for their friends?",
    "What illuminated the night sky?",
    "Who fixed the broken gate in the backyard?",
    "Who sang a duet at the concert?",
    "What glistened in the sunlight?",
    "Whose condition did Dr. Phillips examine carefully?",
    "Who went on a road trip?",
    "What displayed its vibrant feathers?",
    "Who crafted a beautiful sculpture?",
    "Who played a game of chess?",
    "What crackled and warmed the campers?",
    "Who organized a charity event?",
    "Who had a fun day at the amusement park?",
    "Where did the autumn leaves dance in the breeze?",
    "Whose research data did Dr. Adams analyze?",
    "Who baked cookies for their friends?",
    "What illuminated the night sky with bursts of color?",
    "Who planted vegetables in her backyard?",
    "Who fixed the flat tire on his bicycle?",
    "Who delivered a motivational speech?",
    "Who built a magnificent sandcastle on the beach?",
    "What natural phenomenon appeared after the rain?",
    "Who brewed a fresh cup of coffee?",
    "Who played the violin with great passion?",
    "What creatures swam gracefully in the ocean?",
    "Who provided compassionate care to their patients?",
    "Who embarked on an adventure to explore ancient ruins?",
    "What source of light flickered in the dark room?",
    "Who organized a successful charity event?",
    "Who enjoyed a thrilling day at the amusement park?",
    "Where did the cherry blossoms paint a beautiful scene?",
    "Whose research experiment did Dr. Adams conduct in the laboratory?",
    "Who crafted delicious cookies for their friends?",
    "What illuminated the night sky with its radiant glow?",
    "Who fixed the broken gate in their backyard?",
    "Who showcased their impressive vocal talent by singing a duet at the concert?",
    "What natural phenomenon glistened in the sunlight?",
    "Whose condition did Dr. Phillips carefully examine?",
    "Who embarked on an exciting road trip?",
    "What magnificent bird displayed its vibrant feathers?",
    "Who sculpted a breathtaking work of art?",
    "Who engaged in a strategic and thought-provoking game of chess?",
    "What crackled and provided warmth to the campers on a chilly evening?",
    "Whose research study did Dr. Turner undertake?",
    "Who enjoyed a relaxing boat ride on the lake?",
    "What celestial event dazzled the night sky with its brilliance?",
    "Who conducted a cooking class for beginners?",
    "Who prepared a mouthwatering meal that left everyone delighted?",
    "What gentle force swayed the tall grass?",
    "Whose heartfelt speech captivated the audience at the conference?",
    "Who embarked on an exhilarating wildlife safari?",
    "What cast a mesmerizing glow over the dark night?",
    "Who skillfully sculpted a lifelike clay figure?",
    "Who successfully solved a complex math problem?",
    "What crackled and emitted a warm glow, providing comfort on a chilly night?",
    "Whose groundbreaking research experiment did Dr. Wright conduct?",
    "Who spotted rare and exotic birds during their nature walk?",
    "Where did a vibrant rainbow paint a colorful arc across the sky?",
    "Who painted a serene seascape?",
    "Who danced the tango with elegance and grace at the ballroom?",
    "What gentle force kissed the sandy beach with its waves?",
    "Who performed a life-saving surgery?",
    "Who admired breathtaking views during an exhilarating hike?",
    "What shimmered brightly in the clear night sky?",
    "Who baked a scrumptious apple pie?",
    "Who explored the wonders of the coral reef?",
    "What flickered softly, creating a soothing ambiance?",
    "Who provided compassionate medical advice to their patients?",
    "Who collaborated on creating a beautiful artwork?",
    "Where did a serene river meander through the picturesque landscape?",
    "Who organized a successful community event?",
    "Who marveled at the exotic animals in the safari?",
    "Where did the cherry blossoms paint a beautiful scene in the garden?",
    "Whose in-depth research analysis did Dr. Foster perform?",
    "Who twirled gracefully under the moonlit sky?",
    "What roared as it plunged into the pool below, creating a mesmerizing spectacle?",
    "Who sculpted a lifelike clay statue?",
]

EXAMPLE_MIX = [
    "We have a meeting at 10 a.m., don't forget, Mr. Adams!",
    "The quarterly report of Johnson & Sons, Inc., was really impressive.",
    "Our flight is scheduled for 6 p.m., isn't it exciting, Mrs. Thompson?",
    "I was reading vol. 2 of the series and it's fascinating!",
    "Didn't we plan to meet at 7 a.m., Dr. Emily?",
    "When I was in Tex., I learned about their unique culture.",
    "The annual company picnic is at 1 p.m., isn't that great, Mr. Anderson?",
    "According to Thompson et al., the research was groundbreaking.",
    "Remember, the match begins at 9 a.m., Mr. Adams!",
    "I think it's time to wake up, it's already 6 a.m., Emily.",
    "The package, including books, CDs, etc., was delivered yesterday.",
    "Mrs. Thompson, your appointment is at 3 p.m., correct?",
    "Our trip itinerary includes N.Y., Calif., Tex., and more!",
    "I was so impressed with the final project, Mrs. Adams.",
    "The basketball game starts at 8 p.m., get ready, Mr. Thompson!",
    "The annual report, vol. 4, is now available for review.",
    "He leaves the office at 5 p.m., doesn't he, Dr. Emily?",
    "Johnson, Jr., gave a fantastic presentation today!",
    "Isn't it already 7 a.m., Mrs. Adams?",
    "There's a call for you at 1 p.m., Mr. Anderson, don't forget.",
    "I received a call from Mr. Smith, Jr., this morning.",
    "We have to submit the assignment by 5 p.m., isn't it, Emily?",
    "The best time to visit is 3 p.m., don't you think, Mr. Adams?",
    "We are meeting at the Starbucks on 5th St., right Dr. Emily?",
    "This is vol. 3 of the encyclopedia, isn't it fascinating?",
    "We're expecting the delivery at 10 a.m., correct, Mrs. Thompson?",
    "The grand opening of Anderson & Sons, Inc., was quite a spectacle!",
    "Mr. Thompson, your order number is 123, vol. 2.",
    "The next bus to N.Y. leaves at 4 p.m., right, Emily?",
    "Our neighbors, the Johnsons, Jr., are moving to Tex., aren't they?",
    "We're having a meeting at 2 p.m., remember, Mr. Adams!",
    "This painting, i.e., the one on the left, is my favorite, Dr. Emily.",
    "The complete list, including pens, pencils, etc., is on the desk, Mrs. Thompson.",
    "I will be available after 1 p.m., okay, Mr. Anderson?",
    "The party starts at 6 p.m., how exciting, Emily!",
    "The team, including Thompson et al., has done a great job.",
    "We're departing at 5 a.m., early, isn't it, Mr. Adams?",
    "This is vol. 5 of the series, it's the last one, Dr. Emily.",
    "The meeting got postponed to 3 p.m., did you know, Mrs. Thompson?",
    "I must leave by 6 p.m., can we finish by then, Mr. Anderson?",
    "Did you check out the latest vol. 6 of the series, Mr. Adams?",
    "Anderson & Sons, Inc., is opening a new branch in N.Y., did you hear?",
    "The deadline is at 11 p.m., remember, Mrs. Thompson!",
    "Our train leaves at 5 a.m., we need to get some sleep, Emily.",
    "Dr. Emily, your book signing is at 2 p.m., correct?",
    "Mrs. Adams, did you know the Smiths, Jr., are moving to Calif.?",
    "I'll see you at the meeting at 4 p.m., okay, Mr. Anderson?",
    "The bus for Tex. leaves at 1 p.m., we should leave soon.",
    "According to Johnson et al., the climate is changing rapidly.",
    "The concert begins at 7 p.m., isn't it exciting, Dr. Emily?",
    "I finished reading vol. 7, it was captivating, Mrs. Thompson!",
    "I think the sunset in Calif. is at 8 p.m., stunning, isn't it, Mr. Adams?",
    "Did you receive the parcel? It had books, DVDs, etc., Emily.",
    "Remember, our yoga class starts at 9 a.m., Mr. Thompson.",
    "According to this document, Anderson, Jr., won the award!",
    "The event, including dinner, music, etc., starts at 6 p.m., Mrs. Adams.",
    "Your workshop on sustainable living starts at 10 a.m., doesn't it, Dr. Emily?",
    "Our favorite show airs at 8 p.m., we shouldn't miss it, Mr. Anderson!",
    "The final presentation, Mr. Thompson, is at 2 p.m., correct?",
    "The new cafe on Main St., serves the best coffee, doesn't it, Emily?",
    "Mr. Adams, your meeting with Smith & Sons, Inc., is at 1 p.m., right?",
    "We have to leave by 5 a.m., for our trip to N.Y., Mrs. Thompson!",
    "The charity event begins at 3 p.m., we should go, Mr. Anderson.",
    "Isn't the farmer's market open till 6 p.m., Dr. Emily?",
    "I can't believe the weekend is over; it's Monday again, isn't it, Emily?",
    "The launch of the new product line by Johnson & Sons, Inc., was successful, Mrs. Thompson!",
    "Did you know that the bookstore on 7th St., has a sale, Mr. Adams?",
    "I'll meet you at the restaurant at 7 p.m., okay, Dr. Emily?",
    "The marathon starts at 5 a.m., we need to sleep early, Mr. Thompson.",
    "The conference call with the team from Tex. is at 3 p.m., Mrs. Adams.",
    "The newly opened branch of Thompson & Sons, Inc., in Tex., is doing great, Mr. Adams!",
    "The ferry to the island leaves at 8 a.m., don't forget, Mrs. Thompson!",
    "The movie we wanted to watch starts at 7 p.m., isn't it great, Emily?",
    "Remember, Dr. Emily, your TV interview is at 2 p.m.",
    "Did you hear that the Martins, Jr., are moving to Calif., Mr. Anderson?",
    "The gala dinner starts at 8 p.m., remember to dress up, Mr. Thompson!",
    "The flight for N.Y. leaves at 3 p.m., we should leave for the airport soon, Mrs. Adams.",
    "The findings by Wilson et al. have shaken the scientific community, haven't they, Dr. Emily?",
    "The new restaurant on Park St., is getting great reviews, isn't it, Mr. Adams?",
    "The museum exhibit opens at 10 a.m., let's go early to avoid the crowd, Emily.",
    "Mr. Thompson, the meeting with the delegates from N.Y. is at 1 p.m., correct?",
    "Did you finish reading vol. 8 of the series? It's a page-turner, Mrs. Thompson!",
    "The fireworks begin at 9 p.m., we should find a good spot, Mr. Anderson!",
    "The recital, including piano, violin, etc., starts at 6 p.m., we can't be late, Dr. Emily.",
    "The graduation ceremony is at 4 p.m., isn't it exciting, Mrs. Adams?",
    "The fitness class begins at 8 a.m., we need to wake up early, Mr. Adams!",
    "Your appointment with the dentist is at 3 p.m., remember, Emily.",
    "The new policy by Thompson & Sons, Inc., has increased their sales in Calif., hasn't it, Mr. Thompson?",
    "The annual fair starts at 5 p.m., we should go, Dr. Emily.",
    "Isn't it a beautiful day in N.Y., perfect for a walk in Central Park, Mrs. Thompson?",
    "I can't believe it's already 7 a.m., time for breakfast, Emily.",
    "The convention begins at 11 a.m., we should get going, Mr. Anderson.",
    "This is vol. 9 of the series, it's the latest one, Mrs. Adams.",
    "The pool opens at 9 a.m., we should go for a swim, Dr. Emily.",
    "Our flight to Tex. leaves at 1 p.m., we should start packing, Mr. Adams.",
    "The grand opening of Wilson & Sons, Inc., was quite successful, wasn't it, Mr. Thompson?",
    "Your book club meeting is at 2 p.m., don't forget, Mrs. Thompson.",
    "The dance class starts at 4 p.m., we should get ready, Emily.",
    "The seminar by Dr. Johnson, Jr., was quite informative, don't you think, Dr. Emily?",
    "The game starts at 3 p.m., we should grab some snacks, Mr. Anderson.",
    "Isn't the best time to visit the park at 6 p.m., Mrs. Adams?"
]


SEMICOLON_EXAMPLE_SENTENCES = [
    "Dr. Emily is a renowned scientist; her research has made significant contributions to the field of molecular biology.",
    "Mr. Adams is an excellent teacher; he always makes sure each student understands the concepts.",
    "The meeting is scheduled for 10 a.m.; please be sure to arrive on time.",
    "The exhibition was an astounding success; everyone appreciated the artwork on display.",
    "Mrs. Thompson made dinner for the family; it was a delicious meal.",
    "John finished his work; then, he decided to go for a walk.",
    "Jessica is an excellent musician; she plays the violin beautifully.",
    "The park was full of people; children were playing, birds were chirping, and the atmosphere was joyful.",
    "He saw the train approaching; he ran to catch it.",
    "She likes reading books; her favorite author is J.K. Rowling.",
    "The project was a success; however, there are still areas for improvement.",
    "The company announced a new initiative; it focuses on sustainability.",
    "They went to the concert; unfortunately, it started raining.",
    "Mr. Anderson loves traveling; he has visited over 20 countries.",
    "Emily won the competition; she practiced for months to achieve this.",
    "The cake was delicious; I asked for the recipe.",
    "It's a sunny day; let's go for a picnic.",
    "There are many ways to use a semicolon; mastering them can enhance your writing.",
    "Dr. Martinez finished his lecture; he then opened the floor for questions.",
    "She saw a puppy at the pet store; she decided to adopt it."
]

EXAMPLE_SUBJECT_BREAKDOWNS_KEYS = ["subject", "other", "end"]
EXAMPLE_SUBJECT_BREAKDOWNS = [
    [{"fragment": "Gemma, Gillian, and Mike", "type":"subject"}, {"fragment":"are having lunch", "type":"other"}, {"fragment": ".", "type":"end"}],
    [{"fragment": "The ball", "type":"subject"}, {"fragment":"is owned by Alice", "type":"other"}, {"fragment": ".", "type":"end"}],
    [{"fragment": "Alice", "type":"subject"}, {"fragment":"owns the ball", "type":"other"}, {"fragment": ".", "type":"end"}],
    [{"fragment": "Tomorrow,", "type":"other"}, {"fragment":"I", "type":"subject"}, {"fragment":"am going to the store", "type":"other"}, {"fragment": ".", "type":"end"}],
    [{"fragment": "Is there anyone", "type":"other"}, {"fragment":"who", "type":"subject"}, {"fragment":"can help me", "type":"other"}, {"fragment":"?", "type":"end"}],
    [{"fragment": "In the garden,", "type":"other"}, {"fragment":"the children", "type":"subject"}, {"fragment":"were playing", "type":"other"}, {"fragment":".", "type":"end"}],
    [{"fragment": "Under the bright blue sky,", "type":"other"}, {"fragment":"birds", "type":"subject"}, {"fragment":"were singing", "type":"other"}, {"fragment":".", "type":"end"}],
    [{"fragment": "Despite all the challenges,", "type":"other"}, {"fragment":"he", "type":"subject"}, {"fragment":"remained steadfast", "type":"other"}, {"fragment":".", "type":"end"}],
    [{"fragment": "After the movie,", "type":"other"}, {"fragment":"we", "type":"subject"}, {"fragment":"went for dinner", "type":"other"}, {"fragment":".", "type":"end"}],
    [{"fragment": "Running down the street,", "type":"other"}, {"fragment":"the dog", "type":"subject"}, {"fragment":"appeared happy", "type":"other"}, {"fragment":".", "type":"end"}],
    [{"fragment": "Across the room,", "type":"other"}, {"fragment":"John", "type":"subject"}, {"fragment":"gave me a smile", "type":"other"}, {"fragment":".", "type":"end"}],
    [{"fragment": "With a loud bang,", "type":"other"}, {"fragment":"the door", "type":"subject"}, {"fragment":"slammed shut", "type":"other"}, {"fragment":".", "type":"end"}],
    [{"fragment": "On the kitchen table,", "type":"other"}, {"fragment":"a single red rose", "type":"subject"}, {"fragment":"stood in a vase", "type":"other"}, {"fragment":".", "type":"end"}],
    [{"fragment": "Deep within the forest,", "type":"other"}, {"fragment":"a small bird", "type":"subject"}, {"fragment":"made its nest", "type":"other"}, {"fragment":".", "type":"end"}],
    [{"fragment": "Behind the fast-moving clouds,", "type":"other"}, {"fragment":"the moon", "type":"subject"}, {"fragment":"played hide and seek", "type":"other"}, {"fragment":".", "type":"end"}],
    [{"fragment": "Dogs", "type":"subject"}, {"fragment":"are loyal animals", "type":"other"}, {"fragment": ".", "type":"end"}],
    [{"fragment": "She", "type":"subject"}, {"fragment":"loves ice cream", "type":"other"}, {"fragment": ".", "type":"end"}],
    [{"fragment": "The old man", "type":"subject"}, {"fragment":"walked slowly across the street", "type":"other"}, {"fragment": ".", "type":"end"}],
    [{"fragment": "Rain", "type":"subject"}, {"fragment":"falls from the sky", "type":"other"}, {"fragment": ".", "type":"end"}],
    [{"fragment": "Birds", "type":"subject"}, {"fragment":"sing beautifully in the morning", "type":"other"}, {"fragment": ".", "type":"end"}],
    [{"fragment": "The tree", "type":"subject"}, {"fragment":"stands tall in the forest", "type":"other"}, {"fragment": ".", "type":"end"}],
    [{"fragment": "Cats", "type":"subject"}, {"fragment":"like to sleep all day", "type":"other"}, {"fragment": ".", "type":"end"}],
    [{"fragment": "The book", "type":"subject"}, {"fragment":"contains many interesting stories", "type":"other"}, {"fragment": ".", "type":"end"}],
    [{"fragment": "They", "type":"subject"}, {"fragment":"are going to the park", "type":"other"}, {"fragment": ".", "type":"end"}],
    [{"fragment": "Cars", "type":"subject"}, {"fragment":"have become an essential part of our life", "type":"other"}, {"fragment": ".", "type":"end"}],
[{"fragment": "Mr. Johnson", "type":"subject"}, {"fragment":"bought a new car", "type":"other"}, {"fragment": ".", "type":"end"}],
    [{"fragment": "Sarah", "type":"subject"}, {"fragment":"visited her grandmother", "type":"other"}, {"fragment": ".", "type":"end"}],
    [{"fragment": "The dog", "type":"subject"}, {"fragment":"chased its tail", "type":"other"}, {"fragment": ".", "type":"end"}],
    [{"fragment": "Dr. Parker", "type":"subject"}, {"fragment":"examined the patient", "type":"other"}, {"fragment": ".", "type":"end"}],
    [{"fragment": "We", "type":"subject"}, {"fragment":"went swimming in the lake", "type":"other"}, {"fragment": ".", "type":"end"}],
    [{"fragment": "Lisa", "type":"subject"}, {"fragment":"baked a delicious cake", "type":"other"}, {"fragment": ".", "type":"end"}],
    [{"fragment": "The train", "type":"subject"}, {"fragment":"arrived on time", "type":"other"}, {"fragment": ".", "type":"end"}],
    [{"fragment": "Mr. Davis", "type":"subject"}, {"fragment":"walked his dog", "type":"other"}, {"fragment": ".", "type":"end"}],
    [{"fragment": "Emily", "type":"subject"}, {"fragment":"played the piano beautifully", "type":"other"}, {"fragment": ".", "type":"end"}],
    [{"fragment": "The sun", "type":"subject"}, {"fragment":"set behind the mountains", "type":"other"}, {"fragment": ".", "type":"end"}],
[{"fragment": "Dr. Reynolds", "type":"subject"}, {"fragment":"gave a fascinating lecture", "type":"other"}, {"fragment": ".", "type":"end"}],
    [{"fragment": "Sam", "type":"subject"}, {"fragment":"rode his bike to school", "type":"other"}, {"fragment": ".", "type":"end"}],
    [{"fragment": "The cat", "type":"subject"}, {"fragment":"purred contentedly", "type":"other"}, {"fragment": ".", "type":"end"}],
    [{"fragment": "Jessica", "type":"subject"}, {"fragment":"finished her homework early", "type":"other"}, {"fragment": ".", "type":"end"}],
    [{"fragment": "The flowers", "type":"subject"}, {"fragment":"bloomed in the garden", "type":"other"}, {"fragment": ".", "type":"end"}],
    [{"fragment": "Mr. Anderson", "type":"subject"}, {"fragment":"mowed his lawn", "type":"other"}, {"fragment": ".", "type":"end"}],
    [{"fragment": "David", "type":"subject"}, {"fragment":"fixed the broken window", "type":"other"}, {"fragment": ".", "type":"end"}],
    [{"fragment": "Dr. Martinez", "type":"subject"}, {"fragment":"conducted a research study", "type":"other"}, {"fragment": ".", "type":"end"}],
    [{"fragment": "The children", "type":"subject"}, {"fragment":"laughed and played", "type":"other"}, {"fragment": ".", "type":"end"}],
    [{"fragment": "The photo exhibit", "type":"subject"}, {"fragment":"showcased breathtaking images, curated by the talented photographer, Mr. Adams", "type":"other"}, {"fragment": ".", "type":"end"}],
    [{"fragment": "Mr. Thompson", "type":"subject"}, {"fragment":", your order number is 123, vol. 2", "type":"other"}, {"fragment":".", "type":"end"}],
    [{"fragment": "The next bus to N.Y.", "type":"subject"}, {"fragment":"leaves at 4 p.m., right, Emily", "type":"other"}, {"fragment":"?", "type":"end"}],
    [{"fragment": "Our neighbors, the Johnsons, Jr.", "type":"subject"}, {"fragment":"are moving to Tex., aren't they", "type":"other"}, {"fragment":"?", "type":"end"}],
    [{"fragment": "We", "type":"subject"}, {"fragment":"'re having a meeting at 2 p.m., remember, Mr. Adams", "type":"other"}, {"fragment":"!", "type":"end"}],
    [{"fragment": "This painting, i.e., the one on the left", "type":"subject"}, {"fragment":"is my favorite, Dr. Emily", "type":"other"}, {"fragment":".", "type":"end"}],
    [{"fragment": "The complete list, including pens, pencils, etc.", "type":"subject"}, {"fragment":"is on the desk, Mrs. Thompson", "type":"other"}, {"fragment":".", "type":"end"}],
    [{"fragment": "I", "type":"subject"}, {"fragment":"will be available after 1 p.m., okay, Mr. Anderson", "type":"other"}, {"fragment":"?", "type":"end"}],
    [{"fragment": "The party", "type":"subject"}, {"fragment":"starts at 6 p.m., how exciting, Emily", "type":"other"}, {"fragment":"!", "type":"end"}],
    [{"fragment": "The team, including Thompson et al.", "type":"subject"}, {"fragment":"has done a great job", "type":"other"}, {"fragment":".", "type":"end"}],
    [{"fragment": "We", "type":"subject"}, {"fragment":"'re departing at 5 a.m., early, isn't it, Mr. Adams", "type":"other"}, {"fragment":"?", "type":"end"}],
    [{"fragment": "This", "type":"subject"}, {"fragment":"is vol. 5 of the series, it's the last one, Dr. Emily", "type":"other"}, {"fragment":".", "type":"end"}],
    [{"fragment": "The meeting", "type":"subject"}, {"fragment":"got postponed to 3 p.m., did you know, Mrs. Thompson", "type":"other"}, {"fragment":"?", "type":"end"}],
    [{"fragment": "I", "type":"subject"}, {"fragment":"must leave by 6 p.m., can we finish by then, Mr. Anderson", "type":"other"}, {"fragment":"?", "type":"end"}],
    [{"fragment": "You", "type":"subject"}, {"fragment":"did check out the latest vol. 6 of the series, Mr. Adams", "type":"other"}, {"fragment":"?", "type":"end"}],
    [{"fragment": "Anderson & Sons, Inc.", "type":"subject"}, {"fragment":"is opening a new branch in N.Y., did you hear", "type":"other"}, {"fragment":"?", "type":"end"}],
    [{"fragment": "The deadline", "type":"subject"}, {"fragment":"is at 11 p.m., remember, Mrs. Thompson", "type":"other"}, {"fragment":"!", "type":"end"}],
    [{"fragment": "Our train", "type":"subject"}, {"fragment":"leaves at 5 a.m., we need to get some sleep, Emily", "type":"other"}, {"fragment":".", "type":"end"}],
    [{"fragment": "Dr. Emily", "type":"subject"}, {"fragment":", your book signing is at 2 p.m., correct", "type":"other"}, {"fragment":"?", "type":"end"}],
    [{"fragment": "Mrs. Adams", "type":"subject"}, {"fragment":", did you know the Smiths, Jr., are moving to California", "type":"other"}, {"fragment":"?", "type":"end"}],
    [{"fragment": "I", "type":"subject"}, {"fragment":"will see you at the meeting at 4 p.m., okay, Mr. Anderson", "type":"other"}, {"fragment":"?", "type":"end"}],
    [{"fragment": "The bus for Tex.", "type":"subject"}, {"fragment":"leaves at 1 p.m., we should leave soon", "type":"other"}, {"fragment":".", "type":"end"}],
    [{"fragment": "According to Johnson et al.", "type":"subject"}, {"fragment":"the climate is changing rapidly", "type":"other"}, {"fragment":".", "type":"end"}],
    [{"fragment": "The concert", "type":"subject"}, {"fragment":"begins at 7 p.m., isn't it exciting, Dr. Emily", "type":"other"}, {"fragment":"?", "type":"end"}],
    [{"fragment": "I", "type":"subject"}, {"fragment":"finished reading vol. 7, it was captivating, Mrs. Thompson", "type":"other"}, {"fragment":"!", "type":"end"}],
    [{"fragment": "I think the sunset in California", "type":"subject"}, {"fragment":"is at 8 p.m., stunning, isn't it, Mr. Adams", "type":"other"}, {"fragment":"?", "type":"end"}],
    [{"fragment": "You", "type":"subject"}, {"fragment":"did receive the parcel? It had books, DVDs, etc., Emily", "type":"other"}, {"fragment":".", "type":"end"}],
    [{"fragment": "Remember", "type":"subject"}, {"fragment":", our yoga class starts at 9 a.m., Mr. Thompson", "type":"other"}, {"fragment":".", "type":"end"}],
    [{"fragment": "According to this document", "type":"subject"}, {"fragment":"Anderson, Jr., won the award", "type":"other"}, {"fragment":"!", "type":"end"}],
]

EXAMPLE_SUBJECT_VERB_BREAKDOWNS_KEYS = ["subject", "verb", "other", "end of sentence"]
EXAMPLE_SUBJECT_VERB_BREAKDOWNS = [
[{"fragment": "Your access", "type":"subject"}, {"fragment":"to the building will be granted after security checks", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
[{"fragment": "You", "type":"subject"}, {"fragment":"need to", "type":"other"}, {"fragment":"access", "type":"verb"},{"fragment":"the system using the provided password", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
[{"fragment": "The constant ache", "type":"subject"}, {"fragment":"in my back", "type":"other"}, {"fragment":"is getting worse", "type":"verb"}, {"fragment":"!", "type":"end of sentence"}],
[{"fragment": "Can you", "type":"subject"}, {"fragment":"ache", "type":"verb"}, {"fragment":"from loneliness", "type":"other"}, {"fragment":"?", "type":"end of sentence"}],
[{"fragment": "They decided to", "type":"other"}, {"fragment":"act", "type":"verb"}, {"fragment":"on the information immediately", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
[{"fragment": "His act", "type":"subject"}, {"fragment":"was convincing", "type":"verb"}, {"fragment":".", "type":"end of sentence"}],
[{"fragment": "The", "type":"other"}, {"fragment":"mail", "type":"subject"}, {"fragment":"was lost", "type":"verb"}, {"fragment":".", "type":"end of sentence"}],
[{"fragment": "Can you", "type":"subject"}, {"fragment":"mail", "type":"verb"}, {"fragment":"this letter for me", "type":"other"}, {"fragment":"?", "type":"end of sentence"}],
[{"fragment": "Mr. Johnson", "type":"subject"}, {"fragment":"decided to", "type":"other"}, {"fragment":"dust", "type":"verb"}, {"fragment":"his old books at 2 p.m", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
[{"fragment": "The dust", "type":"subject"}, {"fragment":"on the shelves", "type":"other"}, {"fragment":"was thick", "type":"verb"}, {"fragment":".", "type":"end of sentence"}],
[{"fragment": "The act", "type":"subject"}, {"fragment":"of kindness", "type":"other"}, {"fragment":"touched", "type":"verb"}, {"fragment":"her deeply", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
[{"fragment": "I", "type":"subject"}, {"fragment":"will", "type":"other"}, {"fragment":"act", "type":"verb"}, {"fragment":"upon your advice", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
[{"fragment": "His new", "type":"other"}, {"fragment":"dye", "type":"subject"}, {"fragment":"looked", "type":"verb"}, {"fragment":"vibrant", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
[{"fragment": "She", "type":"subject"}, {"fragment":"decided to", "type":"other"}, {"fragment":"dye", "type":"verb"}, {"fragment":"her hair blue", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
[{"fragment": "The man", "type":"subject"}, {"fragment":"at the corner", "type":"other"}, {"fragment":"looked", "type":"verb"}, {"fragment":"familiar", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
[{"fragment": "I", "type":"subject"}, {"fragment":"need to", "type":"other"}, {"fragment":"man", "type":"verb"}, {"fragment":"the station before 3 p.m", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
[{"fragment": "The", "type":"other"}, {"fragment":"address", "type":"subject"}, {"fragment":"is", "type":"verb"}, {"fragment":"incorrect", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
[{"fragment": "Please", "type":"other"}, {"fragment":"address", "type":"verb"}, {"fragment":"the letter to Mr. Smith", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
[{"fragment": "Her voice", "type":"subject"}, {"fragment":"in the valley", "type":"other"}, {"fragment":"began to", "type":"other"}, {"fragment":"echo", "type":"verb"}, {"fragment":".", "type":"end of sentence"}],
[{"fragment": "The echo", "type":"subject"}, {"fragment":"of his words", "type":"other"}, {"fragment":"lingered", "type":"verb"}, {"fragment":"in my mind", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
[{"fragment": "The", "type":"other"}, {"fragment":"march", "type":"subject"}, {"fragment":"was", "type":"verb"}, {"fragment":"long and tiring", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
[{"fragment": "We", "type":"subject"}, {"fragment":"will", "type":"other"}, {"fragment":"march", "type":"verb"}, {"fragment":"at dawn", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
[{"fragment": "Let me", "type":"subject"}, {"fragment":"show", "type":"verb"}, {"fragment":"you the way", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
[{"fragment": "The show", "type":"subject"}, {"fragment":"was", "type":"verb"}, {"fragment":"fantastic", "type":"other"}, {"fragment":"!", "type":"end of sentence"}],
[{"fragment": "My favorite", "type":"other"}, {"fragment":"shop", "type":"subject"}, {"fragment":"is closed.", "type":"verb"}, {"fragment":".", "type":"end of sentence"}],
[{"fragment": "We", "type":"subject"}, {"fragment":"need to", "type":"other"}, {"fragment":"shop", "type":"verb"}, {"fragment":"for groceries", "type":"other"}, {"fragment":".", "type":"end of sentence"}],

[{"fragment": "Mrs. Anderson", "type":"subject"}, {"fragment":"painted", "type":"verb"}, {"fragment":"a beautiful mural", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
[{"fragment": "The dog", "type":"subject"}, {"fragment":"barked", "type":"verb"}, {"fragment":"loudly at the mailman", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
[{"fragment": "Dr. Thompson", "type":"subject"}, {"fragment":"analyzed", "type":"verb"}, {"fragment":"the research data", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
[{"fragment": "John and Emily", "type":"subject"}, {"fragment":"went", "type":"verb"}, {"fragment":"on a hiking trip", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
[{"fragment": "The sunflower", "type":"subject"}, {"fragment":"blossomed", "type":"verb"}, {"fragment":"in the garden", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
[{"fragment": "Mr. Martinez", "type":"subject"}, {"fragment":"taught", "type":"verb"}, {"fragment":"a chemistry class", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
[{"fragment": "Emma and Ethan", "type":"subject"}, {"fragment":"danced", "type":"verb"}, {"fragment":"at the party", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
[{"fragment": "The wind", "type":"subject"}, {"fragment":"whispered", "type":"verb"}, {"fragment":"through the trees", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
[{"fragment": "Dr. Collins", "type":"subject"}, {"fragment":"performed", "type":"verb"}, {"fragment":"a surgery successfully", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
[{"fragment": "Sophia and Daniel", "type":"subject"}, {"fragment":"enjoyed", "type":"verb"}, {"fragment":"a picnic in the park", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
[{"fragment": "The fireflies", "type":"subject"}, {"fragment":"illuminated", "type":"verb"}, {"fragment":"the night sky", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
[{"fragment": "Mrs. Johnson", "type":"subject"}, {"fragment":"planted", "type":"verb"}, {"fragment":"vegetables in her backyard", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
[{"fragment": "Robert", "type":"subject"}, {"fragment":"fixed", "type":"verb"}, {"fragment":"the flat tire on his bicycle", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
[{"fragment": "Dr. Davis", "type":"subject"}, {"fragment":"gave", "type":"verb"}, {"fragment":"a motivational speech", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
[{"fragment": "Oliver and Mia", "type":"subject"}, {"fragment":"built", "type":"verb"}, {"fragment":"a sandcastle on the beach", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
[{"fragment": "The rainbows", "type":"subject"}, {"fragment":"appeared", "type":"verb"}, {"fragment":"after the rain", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
[{"fragment": "Mr. Turner", "type":"subject"}, {"fragment":"brewed", "type":"verb"}, {"fragment":"a fresh cup of coffee", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
[{"fragment": "Grace", "type":"subject"}, {"fragment":"played", "type":"verb"}, {"fragment":"the violin with great passion", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
[{"fragment": "Did you", "type":"subject"}, {"fragment":"hear", "type":"verb"}, {"fragment":"that the Martins, Jr., are moving to Calif., Mr. Anderson", "type":"other"}, {"fragment":"?", "type":"end of sentence"}],
[{"fragment": "The gala dinner", "type":"subject"}, {"fragment":"starts", "type":"verb"}, {"fragment":"at 8 p.m., remember to dress up, Mr. Thompson", "type":"other"}, {"fragment":"!", "type":"end of sentence"}],
[{"fragment": "The flight for N.Y.", "type":"subject"}, {"fragment":"leaves", "type":"verb"}, {"fragment":"at 3 p.m., we should leave for the airport soon, Mrs. Adams", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
[{"fragment": "The findings by Wilson et al.", "type":"subject"}, {"fragment":"have shaken", "type":"verb"}, {"fragment":"the scientific community, haven't they, Dr. Emily", "type":"other"}, {"fragment":"?", "type":"end of sentence"}],
[{"fragment": "The new restaurant on Park St.", "type":"subject"}, {"fragment":"is getting", "type":"verb"}, {"fragment":"great reviews, isn't it, Mr. Adams", "type":"other"}, {"fragment":"?", "type":"end of sentence"}],
[{"fragment": "The museum exhibit", "type":"subject"}, {"fragment":"opens", "type":"verb"}, {"fragment":"at 10 a.m., let's go early to avoid the crowd, Emily", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
[{"fragment": "Mr. Thompson,", "type":"subject"}, {"fragment":"is", "type":"verb"}, {"fragment":"the meeting with the delegates from N.Y. at 1 p.m., correct", "type":"other"}, {"fragment":"?", "type":"end of sentence"}],
[{"fragment": "Did", "type":"other"}, {"fragment":"you", "type":"subject"}, {"fragment":"finish reading", "type":"verb"}, {"fragment":"vol. 8 of the series", "type":"other"}, {"fragment":"?", "type":"end of sentence"}],
    [{"fragment":"It", "type":"subject"}, {"fragment":"'s a page-turner,", "type":"other"}, {"fragment":"Mrs. Thompson", "type":"other"}, {"fragment":"!", "type":"end of sentence"}],[{"fragment": "The fireworks", "type":"subject"}, {"fragment":"begin", "type":"verb"}, {"fragment":"at 9 p.m., we should find a good spot, Mr. Anderson", "type":"other"}, {"fragment":"!", "type":"end of sentence"}],
[{"fragment": "The recital, including piano, violin, etc.", "type":"subject"}, {"fragment":"starts", "type":"verb"}, {"fragment":"at 6 p.m., we can't be late, Dr. Emily", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
[{"fragment": "Wow,", "type":"other"}, {"fragment":"I", "type":"subject"}, {"fragment":"didn't think", "type":"verb"}, {"fragment":"of that", "type":"other"}, {"fragment":"!", "type":"end of sentence"}],
    [{"fragment": "Realistically,", "type":"other"}, {"fragment":"she", "type":"subject"}, {"fragment":"is going", "type":"verb"}, {"fragment":"to need to come home", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
    [ {"fragment":"Slow down", "type":"verb"}, {"fragment":".", "type":"end of sentence"}],
    [{"fragment":"Wait", "type":"verb"}, {"fragment":"for me", "type":"other"}, {"fragment":"!", "type":"end of sentence"}],
    [{"fragment": "Oh no,", "type":"other"}, {"fragment":"the cake", "type":"subject"}, {"fragment":"has fallen", "type":"verb"}, {"fragment":".", "type":"end of sentence"}],
    [{"fragment": "Amazingly,", "type":"other"}, {"fragment":"he", "type":"subject"}, {"fragment":"completed", "type":"verb"}, {"fragment":"the marathon", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
    [{"fragment":"Turn left", "type":"verb"}, {"fragment":"at the next intersection", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
    [{"fragment":"Enjoy", "type":"verb"}, {"fragment":"your meal", "type":"other"}, {"fragment":"!", "type":"end of sentence"}],
    [{"fragment": "Honestly,", "type":"other"}, {"fragment":"we", "type":"subject"}, {"fragment":"never expected", "type":"verb"}, {"fragment":"such a result", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
    [{"fragment": "Surprisingly,", "type":"other"}, {"fragment":"they", "type":"subject"}, {"fragment":"took", "type":"verb"}, {"fragment":"the lead", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
    [{"fragment": "Yikes,", "type":"other"}, {"fragment":"he", "type":"subject"}, {"fragment":"made", "type":"verb"}, {"fragment":"a huge mistake", "type":"other"}, {"fragment":"!", "type":"end of sentence"}],
    [{"fragment": "Well,", "type":"other"}, {"fragment":"I", "type":"subject"}, {"fragment":"think", "type":"verb"}, {"fragment":"it's time to go", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
    [{"fragment": "Wow,", "type":"other"}, {"fragment":"you", "type":"subject"}, {"fragment":"really outdid", "type":"verb"}, {"fragment":"yourself this time", "type":"other"}, {"fragment":"!", "type":"end of sentence"}],
    [{"fragment": "Fortunately,", "type":"other"}, {"fragment":"she", "type":"subject"}, {"fragment":"found", "type":"verb"}, {"fragment":"her keys", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
    [{"fragment": "Regrettably,", "type":"other"}, {"fragment":"we", "type":"subject"}, {"fragment":"must decline", "type":"verb"}, {"fragment":"your invitation", "type":"other"}, {"fragment":".", "type":"end of sentence"}],
    [{"fragment": "Interestingly,", "type":"other"}, {"fragment":"the painting", "type":"subject"}, {"fragment":"depicts", "type":"verb"}, {"fragment":"an unknown woman", "type":"other"}, {"fragment":".", "type":"end of sentence"}]

]









